openapi: 3.0.3

info:
  title: Customer Registration Service API
  description: >
    Customer Registration Service providing secure and reliable APIs
        to create, retrieve, update, partially update, and delete customer
        information, with standardized request handling, tracing, and
        sensitive data protection.
  version: "1.1.0"
  contact:
    name: Dusmanta Jena
    email: support@dj.com

servers:
  - url: http://localhost:8080/api/v1
    description: Local Development Server

tags:
  - name: Customer API
    description: Customer registration and management operations

components:

  parameters:
    X-Correlation-Id:
      name: X-Correlation-Id
      in: header
      required: false
      description: Correlation ID for request tracing across services
      schema:
        type: string
        example: 123e4567-e89b-12d3-a456-426614174000

    PageParam:
      name: page
      in: query
      required: false
      description: Page number (0-based)
      schema:
        type: integer
        default: 0
        example: 0

    SizeParam:
      name: size
      in: query
      required: false
      description: Number of records per page
      schema:
        type: integer
        default: 10
        example: 10

    SortParam:
      name: sort
      in: query
      required: false
      description: Sorting criteria in the format field,asc|desc
      schema:
        type: string
        example: fullName,asc

  schemas:

    CustomerRequest:
      type: object
      required:
        - fullName
        - email
        - mobile
      properties:
        fullName:
          type: string
          example: John Doe
        email:
          type: string
          example: john.doe@gmail.com
        mobile:
          type: string
          example: "9876543210"

    CustomerPatchRequest:
      type: object
      description: Partial update payload for customer
      properties:
        fullName:
          type: string
          example: Updated Name
        email:
          type: string
          example: updated.email@gmail.com
        mobile:
          type: string
          example: "9876500000"

    CustomerResponse:
      type: object
      description: Customer response with masked sensitive fields
      properties:
        id:
          type: integer
          format: int64
          example: 1
        fullName:
          type: string
          example: John Doe
        email:
          type: string
          example: j****@gmail.com
        mobile:
          type: string
          example: 98******10

    PageCustomerResponse:
      type: object
      description: Paginated customer response
      properties:
        content:
          type: array
          items:
            $ref: "#/components/schemas/CustomerResponse"
        totalElements:
          type: integer
          example: 25
        totalPages:
          type: integer
          example: 5
        size:
          type: integer
          example: 5
        number:
          type: integer
          example: 0
        first:
          type: boolean
          example: true
        last:
          type: boolean
          example: false

    ErrorResponse:
      type: object
      description: Standard error response
      properties:
        timestamp:
          type: string
          format: date-time
        status:
          type: integer
          example: 404
        error:
          type: string
          example: Not Found
        message:
          type: string
          example: Customer not found
        path:
          type: string
          example: /api/v1/customers/1

paths:

  /customers:
    get:
      tags:
        - Customer API
      summary: Retrieve customers
      description: >
        Retrieves customer records based on optional query parameters.
        Supports filtering, pagination, and sorting.
        If no filters are provided, all customers are returned in a paginated format.
      parameters:
        - $ref: "#/components/parameters/X-Correlation-Id"
        - name: name
          in: query
          required: false
          description: Search customers by full name (partial match)
          schema:
            type: string
        - name: email
          in: query
          required: false
          description: Search customers by email (partial match)
          schema:
            type: string
        - name: mobile
          in: query
          required: false
          description: Search customers by mobile number (partial match)
          schema:
            type: string
        - $ref: "#/components/parameters/PageParam"
        - $ref: "#/components/parameters/SizeParam"
        - $ref: "#/components/parameters/SortParam"
      responses:
        "200":
          description: Customers retrieved successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PageCustomerResponse"

    post:
      tags:
        - Customer API
      summary: Create a new customer
      parameters:
        - $ref: "#/components/parameters/X-Correlation-Id"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CustomerRequest"
      responses:
        "201":
          description: Customer created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CustomerResponse"
        "400":
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /customers/{id}:
    get:
      tags:
        - Customer API
      summary: Get customer by ID
      parameters:
        - $ref: "#/components/parameters/X-Correlation-Id"
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Customer found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CustomerResponse"
        "404":
          description: Customer not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

    put:
      tags:
        - Customer API
      summary: Update customer (full)
      parameters:
        - $ref: "#/components/parameters/X-Correlation-Id"
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CustomerRequest"
      responses:
        "200":
          description: Customer updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CustomerResponse"
        "404":
          description: Customer not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

    patch:
      tags:
        - Customer API
      summary: Partially update customer
      parameters:
        - $ref: "#/components/parameters/X-Correlation-Id"
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CustomerPatchRequest"
      responses:
        "200":
          description: Customer partially updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CustomerResponse"
        "404":
          description: Customer not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

    delete:
      tags:
        - Customer API
      summary: Delete customer
      parameters:
        - $ref: "#/components/parameters/X-Correlation-Id"
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "204":
          description: Customer deleted successfully
        "404":
          description: Customer not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
